//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/util/DistackRemoteTCPPayload.msg.
//

#ifndef _DISTACKREMOTETCPPAYLOAD_M_H_
#define _DISTACKREMOTETCPPAYLOAD_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef REASE_API 
#  if defined(REASE_EXPORT)
#    define REASE_API  OPP_DLLEXPORT
#  elif defined(REASE_IMPORT)
#    define REASE_API  OPP_DLLIMPORT
#  else
#    define REASE_API 
#  endif
#endif

// cplusplus {{
#include "ReaSEDefs.h"
// }}



/**
 * Class generated from <tt>applications/util/DistackRemoteTCPPayload.msg</tt> by opp_msgc.
 * <pre>
 * packet DistackRemoteTCPPayload
 * {
 * 	char header[];
 * 	char data[];
 * 	bool xml;
 * }
 * </pre>
 */
class REASE_API DistackRemoteTCPPayload : public ::cPacket
{
  protected:
    char *header_var; // array ptr
    unsigned int header_arraysize;
    char *data_var; // array ptr
    unsigned int data_arraysize;
    bool xml_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DistackRemoteTCPPayload&);

  public:
    DistackRemoteTCPPayload(const char *name=NULL, int kind=0);
    DistackRemoteTCPPayload(const DistackRemoteTCPPayload& other);
    virtual ~DistackRemoteTCPPayload();
    DistackRemoteTCPPayload& operator=(const DistackRemoteTCPPayload& other);
    virtual DistackRemoteTCPPayload *dup() const {return new DistackRemoteTCPPayload(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setHeaderArraySize(unsigned int size);
    virtual unsigned int getHeaderArraySize() const;
    virtual char getHeader(unsigned int k) const;
    virtual void setHeader(unsigned int k, char header_var);
    virtual void setDataArraySize(unsigned int size);
    virtual unsigned int getDataArraySize() const;
    virtual char getData(unsigned int k) const;
    virtual void setData(unsigned int k, char data_var);
    virtual bool getXml() const;
    virtual void setXml(bool xml_var);
};

inline void doPacking(cCommBuffer *b, DistackRemoteTCPPayload& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DistackRemoteTCPPayload& obj) {obj.parsimUnpack(b);}


#endif // _DISTACKREMOTETCPPAYLOAD_M_H_
